services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fuhrpark_manager
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - '8025:8025'

  api:
    build:
      context: ./apps/api
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: mysql://root:root@db:3306/fuhrpark_manager
      APP_URL: http://localhost:3000
      API_URL: http://localhost:4000
    ports:
      - '4000:4000'

  web:
    build:
      context: ./apps/web
    depends_on:
      - api
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - '3000:3000'

volumes:
  db-data:
