name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint frontend
        run: npm run web:lint

      - name: Lint backend
        run: npm run api:lint

      - name: Build backend
        env:
          DATABASE_URL: mysql://root:root@localhost:3306/fuhrpark_manager
        run: npm run api:build

      - name: Build frontend
        run: npm run web:build
